version: 2.1

parameters:
  cipool_run_id:
    type: string
    default: ""
  cipool_ticket:
    type: string
    default: ""
  cipool_broker_url:
    type: string
    default: ""
  cipool_job:
    type: string
    default: ""
  cipool_repository:
    type: string
    default: ""
  cipool_sha:
    type: string
    default: ""
  cipool_branch:
    type: string
    default: ""

jobs:
  execute:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - run:
          name: CI Pool executor
          command: |
            chmod +x ./scripts/execute.sh
            ./scripts/execute.sh \
              '<< pipeline.parameters.cipool_run_id >>' \
              '<< pipeline.parameters.cipool_ticket >>' \
              '<< pipeline.parameters.cipool_broker_url >>'

workflows:
  execute:
    jobs:
      - execute
